package com.example.dairy.domain;
import jakarta.persistence.*; import java.time.Instant; import java.util.ArrayList; import java.util.List; import java.util.UUID;
@Entity @Table(name="comparisons")
public class Comparison {
 @Id private UUID id;
 @ManyToOne(fetch=FetchType.LAZY,optional=false) @JoinColumn(name="segment_id") private BatchSegment segment;
 @ManyToOne(fetch=FetchType.LAZY,optional=false) @JoinColumn(name="before_sample_id") private Sample beforeSample;
 @ManyToOne(fetch=FetchType.LAZY,optional=false) @JoinColumn(name="after_sample_id") private Sample afterSample;
 @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="pressure_mapping_id") private PressureCalibrationMapping pressureMapping;
 @Enumerated(EnumType.STRING) @Column(nullable=false,length=16) private Enums.ComparisonStatus status;
 @Column(name="auto_generated",nullable=false) private boolean autoGenerated;
 @Column(name="proposed_by",nullable=false) private String proposedBy;
 @Column(name="proposed_at",nullable=false) private Instant proposedAt=Instant.now();
 @Column(name="confirmed_by") private String confirmedBy;
 @Column(name="confirmed_at") private Instant confirmedAt;
 @Version private long lockVersion;
 @OneToMany(mappedBy="comparison",cascade=CascadeType.ALL,orphanRemoval=true) private List<ComparisonReason> reasons=new ArrayList<>();
 @OneToOne(mappedBy="comparison",cascade=CascadeType.ALL,orphanRemoval=true,fetch=FetchType.LAZY) private ComparisonDependency dependency;
 @PrePersist void assign(){if(id==null)id=UUID.randomUUID();}
 public UUID getId(){return id;} public void setId(UUID v){id=v;}
 public BatchSegment getSegment(){return segment;} public void setSegment(BatchSegment v){segment=v;}
 public Sample getBeforeSample(){return beforeSample;} public void setBeforeSample(Sample v){beforeSample=v;}
 public Sample getAfterSample(){return afterSample;} public void setAfterSample(Sample v){afterSample=v;}
 public PressureCalibrationMapping getPressureMapping(){return pressureMapping;} public void setPressureMapping(PressureCalibrationMapping v){pressureMapping=v;}
 public Enums.ComparisonStatus getStatus(){return status;} public void setStatus(Enums.ComparisonStatus v){status=v;}
 public boolean isAutoGenerated(){return autoGenerated;} public void setAutoGenerated(boolean v){autoGenerated=v;}
 public String getProposedBy(){return proposedBy;} public void setProposedBy(String v){proposedBy=v;}
 public Instant getProposedAt(){return proposedAt;} public void setProposedAt(Instant v){proposedAt=v;}
 public String getConfirmedBy(){return confirmedBy;} public void setConfirmedBy(String v){confirmedBy=v;}
 public Instant getConfirmedAt(){return confirmedAt;} public void setConfirmedAt(Instant v){confirmedAt=v;}
 public long getLockVersion(){return lockVersion;} public void setLockVersion(long v){lockVersion=v;}
 public List<ComparisonReason> getReasons(){return reasons;}
 public ComparisonDependency getDependency(){return dependency;} public void setDependency(ComparisonDependency v){dependency=v;}
}
