import type { Comparison } from '../types';
import { DistributionChart, PressureChart } from './Charts';
import { Reasons } from './Reasons';

export function ComparisonCard({ comparison, canConfirm, onRefresh, onConfirm }:{
  comparison: Comparison; canConfirm:boolean; onRefresh:(id:string)=>void; onConfirm:(id:string)=>void;
}) {
  return <article className={`comparison ${comparison.status.toLowerCase()}`}>
    <header><h3>{comparison.before.sampleCode} → {comparison.after.sampleCode}</h3>
      <span className="badge">{comparison.status}</span><span>{comparison.autoGenerated?'自动候选':'人工候选'}</span>
      <span>修正级别 {comparison.correctionLevel ?? '—'}</span></header>
    <p className="meta">前样到达 {fmt(comparison.before.receivedAt)}；实际取样 {fmt(comparison.before.sampledAt)}。
      后样到达 {fmt(comparison.after.receivedAt)}；实际取样 {fmt(comparison.after.sampledAt)}。
      粒度算法 {comparison.before.algorithm} {comparison.before.algorithmVersion} / {comparison.after.algorithmVersion}
    </p>
    <div className="grid"><PressureChart before={comparison.before.pressure} after={comparison.after.pressure}/><Reasons reasons={comparison.reasons}/></div>
    <div className="grid"><DistributionChart before={comparison.before.distribution} after={comparison.after.distribution}/>
      <div className="actions"><p>系统只提出候选和列原因，不推荐压力、不控制均质机。</p>
        {canConfirm && <button onClick={()=>onRefresh(comparison.id)}>刷新规则/依赖</button>}
        {canConfirm && <button className="primary" disabled={comparison.reasons.length>0} onClick={()=>onConfirm(comparison.id)}>人工确认候选</button>}
        {comparison.confirmedBy && <p>确认人：{comparison.confirmedBy} @ {fmt(comparison.confirmedAt)}</p>}
      </div></div>
  </article>;
}
function fmt(v?:string){ return v ? new Date(v).toLocaleString() : '—'; }
