package com.example.dairy.dto;

import com.example.dairy.domain.Enums;
import jakarta.validation.constraints.*;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

public final class Dtos { private Dtos() {}

public record IdResponse(UUID id) {}
public record ReasonResponse(String code, String detail, String severity) {}
public record PointResponse(int order, String rawLabel, BigDecimal rawBar, BigDecimal correctedBar, UUID mappingId, String canonicalLabel, Instant measuredAt) {}
public record BinResponse(BigDecimal binUm, BigDecimal volumePct) {}
public record SampleSide(UUID id, String sampleCode, Enums.SampleType type, Enums.Layer layer, Instant sampledAt, Instant receivedAt,
                         UUID measurementPointId, String algorithm, String algorithmVersion, UUID algorithmVersionId,
                         List<PointResponse> pressure, List<BinResponse> distribution) {}
public record SegmentResponse(UUID id, String code, String valveGroup, String samplingLine, String productBatch,
                              String targetStage, Instant baselineStart, Instant baselineEnd,
                              Instant stableStart, Instant stableEnd, String status, long version) {}
public record SegmentDetailResponse(SegmentResponse segment, List<SampleSide> samples,
                                    List<ComparisonResponse> comparisons, ImportSummary imports, ReviewSummary review) {}
public record ImportSummary(String status, int total, int successful, int failed, List<FileSummary> files) {}
public record FileSummary(UUID id, String filename, String status, int attempts, String error, Instant processedAt) {}
public record ReviewSummary(String status, String decision, String lockedBy, Instant lockedAt, String decisionBy, Instant decisionAt, String sha256) {}
public record ComparisonResponse(UUID id, String status, boolean autoGenerated, SampleSide before, SampleSide after,
                                 UUID pressureMappingId, Integer correctionLevel, String proposedBy, Instant proposedAt,
                                 String confirmedBy, Instant confirmedAt, List<ReasonResponse> reasons) {}
public record PressureMappingResponse(UUID id, String rawLabel, String canonicalLabel, int correctionLevel, int version,
                                      BigDecimal slope, BigDecimal intercept, Instant effectiveFrom, boolean active) {}
public record CorrectionRequest(@NotNull UUID measurementPointId, @NotBlank String rawLabel,
                                @NotBlank String canonicalLabel, @NotNull @PositiveOrZero Integer correctionLevel,
                                @NotNull @DecimalMin("0.000001") BigDecimal slope,
                                @NotNull BigDecimal intercept, @NotBlank String reason) {}
public record ManualPairRequest(@NotNull UUID beforeSampleId, @NotNull UUID afterSampleId) {}
public record ReviewDecisionRequest(@NotNull Enums.ReviewDecision decision, String notes) {}
}
