// @vitest-environment jsdom
import { render, screen } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';
import { ComparisonCard } from '../components/ComparisonCard';
import type { Comparison, SampleSide } from '../types';

const sample = (code:string, version:string):SampleSide=>({
  id:'s-id',sampleCode:code,type:code.includes('BEFORE')?'BEFORE':'AFTER',layer:'MIDDLE',
  sampledAt:'2026-09-30T10:03:00Z',receivedAt:'2026-09-30T10:30:00Z',measurementPointId:'p',
  algorithm:'Fraunberger-LDD',algorithmVersion:version,algorithmVersionId:'a',
  pressure:[{order:1,rawLabel:'P-HIGH',rawBar:150,correctedBar:150,mappingId:'m',canonicalLabel:'HIGH',measuredAt:'x'}],
  distribution:[{binUm:1,volumePct:5}]
});
const comparison = (overrides:Partial<Comparison>):Comparison => ({
  id:'c',status:'BLOCKED',autoGenerated:true,before:sample('B-BEFORE','1.8.2'),after:sample('A-AFTER','2.0.0'),
  pressureMappingId:'m',correctionLevel:0,proposedBy:'system',proposedAt:'x',reasons:[
    {code:'PARTICLE_ALGORITHM_MISMATCH',detail:'粒度算法版本不同',severity:'BLOCKER'}
  ], ...overrides
});

describe('ComparisonCard', () => {
  it('在曲线旁显示算法换版不可比原因并禁用确认', () => {
    render(<ComparisonCard comparison={comparison({})} canConfirm={true} onRefresh={vi.fn()} onConfirm={vi.fn()}/>);
    expect(screen.getByText('PARTICLE_ALGORITHM_MISMATCH')).toBeTruthy();
    expect((screen.getByText('人工确认候选') as HTMLButtonElement).disabled).toBe(true);
  });
  it('无原因时允许人工确认', () => {
    render(<ComparisonCard comparison={comparison({status:'PROPOSED',reasons:[]})} canConfirm={true} onRefresh={vi.fn()} onConfirm={vi.fn()}/>);
    expect((screen.getByText('人工确认候选') as HTMLButtonElement).disabled).toBe(false);
  });
});
