package com.example.dairy.service;

import com.example.dairy.domain.*;
import com.example.dairy.dto.Dtos.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Comparator;
import java.util.List;

@Service
public class DtoAssembler {
    @Transactional(readOnly=true)
    public SegmentResponse segment(BatchSegment s) {
        return new SegmentResponse(s.getId(), s.getCode(), s.getValveGroup().getCode(),
                s.getSamplingLine().getCode(), s.getProductBatch().getBatchNo(), s.getTargetStageLabel(),
                s.getBaselineStart(), s.getBaselineEnd(), s.getStableStart(), s.getStableEnd(),
                s.getStatus().name(), s.getLockVersion());
    }

    @Transactional(readOnly=true)
    public SampleSide sample(Sample s) {
        var p = s.getAlgorithmVersion();
        List<PointResponse> points = s.getPressureReadings().stream()
                .sorted(Comparator.comparingInt(PressureReading::getStageOrder))
                .map(r -> new PointResponse(r.getStageOrder(), r.getRawLabel(), r.getRawValueBar(),
                        r.getCorrectedValueBar(), r.getMapping()==null?null:r.getMapping().getId(),
                        r.getMapping()==null?"UNMAPPED":r.getMapping().getCanonicalStageLabel(), r.getMeasuredAt()))
                .toList();
        List<BinResponse> bins = s.getParticleDistributions().stream()
                .sorted(Comparator.comparing(ParticleDistribution::getBinUm))
                .map(d -> new BinResponse(d.getBinUm(), d.getVolumePct())).toList();
        return new SampleSide(s.getId(), s.getSampleCode(),
                s.getSampleType(), s.getLayer(), s.getSampledAt(), s.getReceivedAt(),
                s.getMeasurementPoint().getId(), p.getAlgorithmName(), p.getVersion(), p.getId(), points, bins);
    }

    @Transactional(readOnly=true)
    public ComparisonResponse comparison(Comparison c) {
        Integer correctionLevel = c.getPressureMapping()==null ? null : c.getPressureMapping().getCorrectionLevel();
        return new ComparisonResponse(c.getId(), c.getStatus().name(), c.isAutoGenerated(),
                sample(c.getBeforeSample()), sample(c.getAfterSample()),
                c.getPressureMapping()==null?null:c.getPressureMapping().getId(), correctionLevel,
                c.getProposedBy(), c.getProposedAt(), c.getConfirmedBy(), c.getConfirmedAt(),
                c.getReasons().stream().map(r -> new ReasonResponse(r.getCode(), r.getDetail(), r.getSeverity().name())).toList());
    }
}
