package com.example.dairy.service;

import com.example.dairy.domain.*;
import com.example.dairy.dto.Dtos.ManualPairRequest;
import com.example.dairy.repository.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.*;

@Service
public class PairingService {
    private static final List<Enums.ComparisonStatus> ACTIVE = List.of(
            Enums.ComparisonStatus.PROPOSED, Enums.ComparisonStatus.BLOCKED,
            Enums.ComparisonStatus.STALE, Enums.ComparisonStatus.CONFIRMED);

    private final BatchSegmentRepository segments;
    private final SampleRepository samples;
    private final ComparisonRepository comparisons;
    private final EligibilityService eligibility;
    private final DtoAssembler assembler;

    public PairingService(BatchSegmentRepository segments, SampleRepository samples,
                          ComparisonRepository comparisons, EligibilityService eligibility, DtoAssembler assembler) {
        this.segments = segments; this.samples = samples; this.comparisons = comparisons;
        this.eligibility = eligibility; this.assembler = assembler;
    }

    @Transactional
    public int autoPair(UUID segmentId, String actor) {
        BatchSegment segment = segments.findById(segmentId).orElseThrow(() -> new NotFoundException("批段不存在"));
        List<Sample> all = samples.findBySegmentIdOrderBySampledAtAsc(segmentId);
        List<Sample> befores = all.stream().filter(s -> s.getSampleType()==Enums.SampleType.BEFORE).toList();
        List<Sample> afters = all.stream().filter(s -> s.getSampleType()==Enums.SampleType.AFTER).toList();
        final int[] created = {0};
        for (Sample after : afters) {
            if (comparisons.findFirstByAfterSample_IdAndStatusIn(after.getId(), ACTIVE).isPresent()) continue;
            befores.stream()
                    .filter(b -> b.getLayer() == after.getLayer())
                    .filter(b -> b.getSampledAt().isBefore(after.getSampledAt()))
                    .max(Comparator.comparing(Sample::getSampledAt))
                    .ifPresent(before -> {
                        createComparison(segment, before, after, true, actor);
                        created[0]++;
                    });
            // 一个前样可匹配多个后样压力阶段；没有匹配的后样会在 UI 上显示为“无候选”。
        }
        return created[0];
    }

    @Transactional
    public Comparison manualPair(UUID segmentId, ManualPairRequest request, String actor) {
        BatchSegment segment = segments.findById(segmentId).orElseThrow(() -> new NotFoundException("批段不存在"));
        Sample before = samples.findById(request.beforeSampleId()).orElseThrow(() -> new NotFoundException("前样不存在"));
        Sample after = samples.findById(request.afterSampleId()).orElseThrow(() -> new NotFoundException("后样不存在"));
        if (!before.getSegment().getId().equals(segmentId) || !after.getSegment().getId().equals(segmentId))
            throw new ValidationException("两个样品必须属于当前批段。");
        comparisons.findFirstByAfterSample_IdAndStatusIn(after.getId(), ACTIVE).ifPresent(existing -> {
            if (!existing.getBeforeSample().getId().equals(before.getId())) existing.setStatus(Enums.ComparisonStatus.SUPERSEDED);
        });
        return comparisons.findBySegmentIdOrderByProposedAtDesc(segmentId).stream()
                .filter(c -> c.getStatus()!=Enums.ComparisonStatus.SUPERSEDED
                        && c.getBeforeSample().getId().equals(before.getId())
                        && c.getAfterSample().getId().equals(after.getId()))
                .findFirst().orElseGet(() -> createComparison(segment, before, after, false, actor));
    }

    @Transactional
    public Comparison refresh(UUID comparisonId) {
        Comparison c = comparisons.lockById(comparisonId).orElseThrow(() -> new NotFoundException("比较不存在"));
        if (c.getSegment().getStatus() == Enums.SegmentStatus.ISSUED) throw new ConflictException("已签发证据不能刷新。");
        return populate(c, eligibility.evaluate(c.getSegment(), c.getBeforeSample(), c.getAfterSample()), false);
    }

    @Transactional
    public Comparison confirm(UUID comparisonId, String actor) {
        Comparison c = comparisons.lockById(comparisonId).orElseThrow(() -> new NotFoundException("比较不存在"));
        if (c.getSegment().getStatus() != Enums.SegmentStatus.OPEN) throw new ConflictException("批段锁定后不能改变候选确认。");
        EligibilityResult result = eligibility.evaluate(c.getSegment(), c.getBeforeSample(), c.getAfterSample());
        populate(c, result, c.isAutoGenerated());
        if (!result.comparable()) throw new ConflictException("存在不可比原因，不能确认候选。");
        c.setStatus(Enums.ComparisonStatus.CONFIRMED);
        c.setConfirmedBy(actor);
        c.setConfirmedAt(java.time.Instant.now());
        return c;
    }

    private Comparison createComparison(BatchSegment segment, Sample before, Sample after, boolean auto, String actor) {
        Comparison c = new Comparison();
        c.setSegment(segment); c.setBeforeSample(before); c.setAfterSample(after);
        c.setAutoGenerated(auto); c.setProposedBy(actor); c.setProposedAt(java.time.Instant.now());
        comparisons.saveAndFlush(c);
        return populate(c, eligibility.evaluate(segment, before, after), auto);
    }

    private Comparison populate(Comparison c, EligibilityResult result, boolean resetConfirmation) {
        c.getReasons().clear();
        for (var reason : result.blockerReasons()) {
            ComparisonReason entity = new ComparisonReason();
            entity.setComparison(c);
            entity.setCode(reason.code()); entity.setDetail(reason.detail());
            entity.setSeverity(Enums.Severity.valueOf(reason.severity()));
            c.getReasons().add(entity);
        }
        c.setPressureMapping(result.pressureMapping());
        ComparisonDependency dep = c.getDependency();
        if (dep == null) { dep = new ComparisonDependency(); dep.setComparison(c); c.setDependency(dep); }
        dep.setPressureMapping(result.pressureMapping());
        dep.setParticleAlgorithmBefore(c.getBeforeSample().getAlgorithmVersion());
        dep.setParticleAlgorithmAfter(c.getAfterSample().getAlgorithmVersion());
        c.setStatus(result.comparable() ? Enums.ComparisonStatus.PROPOSED : Enums.ComparisonStatus.BLOCKED);
        if (resetConfirmation && c.getStatus() != Enums.ComparisonStatus.CONFIRMED) {
            c.setConfirmedBy(null); c.setConfirmedAt(null);
        }
        return comparisons.save(c);
    }
}
