import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {DistributionChart} from './components/DistributionChart.jsx';
import {PressureStageChart} from './components/PressureStageChart.jsx';
import {IncomparableReasons} from './components/IncomparableReasons.jsx';
import './styles.css';

const auth = {operator:'operator:password', analyst:'analyst:password', reviewer:'reviewer:password'};
function headers(extra={}) { return {...extra, Authorization:'Basic '+btoa(auth[localStorage.getItem('role')||'analyst'])}; }
function api(path, options={}) { return fetch(path,{credentials:'include',...options,headers:headers(options.headers)}).then(async r=>{const text=await r.text(); const body=text?JSON.parse(text):null; if(!r.ok) throw new Error(body?.error||r.statusText); return body;}); }
function App(){const [batches,setBatches]=useState([]),[batchId,setBatchId]=useState(1),[comparisons,setComparisons]=useState([]),[pressure,setPressure]=useState([]),[selected,setSelected]=useState(null),[role,setRole]=useState(localStorage.getItem('role')||'analyst'),[message,setMessage]=useState('系统只做证据复核：不推荐压力，不控制均质机。');
 useEffect(()=>{api('/api/batches').then(setBatches).catch(e=>setMessage(e.message));},[]);
 const load=(id=batchId)=>Promise.all([api(`/api/comparisons/batch/${id}`),api(`/api/batches/${id}/pressure`)]).then(([cs,ps])=>{setComparisons(cs);setPressure(ps);setSelected(cs[0]||null);}).catch(e=>setMessage(e.message));
 useEffect(()=>{load(batchId);},[batchId]);
 const act=async fn=>{try{await fn();setMessage('操作完成');load();}catch(e){setMessage(e.message);}};
 return <div className="shell"><header><div><h1>乳品均质证据复核</h1><p>压力阶段 × 粒径分布 × 审核证据快照</p></div><label>身份<select value={role} onChange={e=>{localStorage.setItem('role',e.target.value);setRole(e.target.value);}}><option value="operator">操作员</option><option value="analyst">实验员</option><option value="reviewer">审核员</option></select></label></header><div className="notice">{message}</div><main><section className="panel"><h2>批段与压力阶段</h2><select value={batchId} onChange={e=>setBatchId(Number(e.target.value))}>{batches.map(b=><option key={b.id} value={b.id}>{b.batchNumber} · {b.productName}</option>)}</select><PressureStageChart points={pressure}/><ImportPanel notify={setMessage} reload={load}/></section><section className="panel wide"><h2>一对多候选配对</h2><div className="toolbar"><button onClick={()=>act(()=>api(`/api/comparisons/auto-pair/batches/${batchId}`,{method:'POST'}))}>重新自动配对</button><button onClick={()=>act(()=>api('/api/pressure-mappings/correct',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({valveGroupId:1,changeSummary:'压力标签互换验证',items:[{rawLabel:'P1',calibratedStageCode:'STAGE_220',nominalPressureBar:220,displayOrder:20},{rawLabel:'P2',calibratedStageCode:'STAGE_180',nominalPressureBar:180,displayOrder:10}]})}))}>实验员：压力互换修正</button></div><div className="candidate-grid">{comparisons.map(c=><article key={c.id} className={selected?.id===c.id?'active card':'card'} onClick={()=>setSelected(c)}><b>{c.stageCode||'未解析阶段'}</b><span>{c.before?.sampleCode} → {c.after?.sampleCode}</span><em className={c.comparable?'ok':'bad'}>{c.status} · {c.comparable?'可比':'不可比'}</em></article>)}</div>{selected&&<Details c={selected} notify={setMessage} reload={load}/>}</section></main></div>}
function ImportPanel({notify,reload}){const [type,setType]=useState('PRESSURE_CSV');return <div className="import"><select value={type} onChange={e=>setType(e.target.value)}><option>PRESSURE_CSV</option><option>PARTICLE_CSV</option></select><input type="file" multiple accept=".csv" onChange={async e=>{const fd=new FormData();[...e.target.files].forEach(f=>fd.append('files',f));fd.append('type',type);try{const r=await fetch('/api/imports',{method:'POST',credentials:'include',headers:{Authorization:'Basic '+btoa(auth[localStorage.getItem('role')||'analyst'])},body:fd});const job=await r.json();if(job.error)throw Error(job.error);await api('/api/imports/process-next',{method:'POST'});notify('导入任务已处理');reload();}catch(err){notify(err.message);}}}/><p>每个文件独立事务；失败文件可重试，任务显示 PARTIAL_SUCCESS。</p></div>}
function Details({c,notify,reload}){const act=async (path,body)=>{try{await api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});notify('操作完成');reload();}catch(e){notify(e.message);}};return <div className="details"><div className="curves"><DistributionChart title="前样粒径" curve={c.before}/><DistributionChart title="后样粒径" curve={c.after}/></div><IncomparableReasons findings={c.findings}/><div className="toolbar"><button disabled={!c.comparable} onClick={()=>act(`/api/comparisons/${c.id}/confirm`)}>人工确认</button><button onClick={()=>act(`/api/comparisons/${c.id}/reject`)}>退回候选</button><button onClick={()=>act(`/api/reviews/comparisons/${c.id}/request`)}>送审</button><button onClick={()=>act(`/api/reviews/comparisons/${c.id}/decision`,{approve:true,decisionNote:'复核通过'})}>审核员批准锁定</button></div><p>审核状态：{c.reviewStatus||'未送审'} {c.reviewedBy?`· ${c.reviewedBy}`:''}</p><code>{c.fingerprint}</code></div>}
createRoot(document.getElementById('root')).render(<App/>);
