export type Status = 'PROPOSED'|'BLOCKED'|'STALE'|'CONFIRMED'|'SUPERSEDED';
export interface Reason { code: string; detail: string; severity: 'BLOCKER'|'WARNING' }
export interface Point { order: number; rawLabel: string; rawBar: number; correctedBar?: number; mappingId?: string; canonicalLabel: string; measuredAt: string }
export interface Bin { binUm: number; volumePct: number }
export interface SampleSide {
  id:string; sampleCode: string; type: 'BEFORE'|'AFTER'; layer: 'TOP'|'MIDDLE'|'BOTTOM'; sampledAt: string; receivedAt: string;
  measurementPointId: string; algorithm: string; algorithmVersion: string; algorithmVersionId: string; pressure: Point[]; distribution: Bin[];
}
export interface Comparison {
  id: string; status: Status; autoGenerated: boolean; before: SampleSide; after: SampleSide;
  pressureMappingId?: string; correctionLevel?: number; proposedBy: string; proposedAt: string;
  confirmedBy?: string; confirmedAt?: string; reasons: Reason[];
}
export interface Segment { id:string; code:string; valveGroup:string; samplingLine:string; productBatch:string; targetStage:string; baselineStart:string; baselineEnd:string; stableStart:string; stableEnd:string; status:string; version:number }
export interface FileSummary { id:string; filename:string; status:string; attempts:number; error?:string; processedAt?:string }
export interface ImportSummary { status:string; total:number; successful:number; failed:number; files:FileSummary[] }
export interface ReviewSummary { status:string; decision?:string; lockedBy:string; lockedAt:string; decisionBy?:string; decisionAt?:string; sha256?:string }
export interface SegmentDetail { segment:Segment; samples:SampleSide[]; comparisons:Comparison[]; imports:ImportSummary; review?:ReviewSummary }
export interface Credentials { username:string; password:string }
